config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  namespace :admin do
    resources :books do
      get 'stats', on: :collection
    end
    root 'books#index'
  end

  resources :users, only: [:show]

  resources :books, only: [:index, :show, :update]

  resources :carts

  resources :orders, only: [:index, :create]

  resources :opinions, only: [:index, :create]

  resources :ratings, only: [:index, :create]

  root 'books#index'
end

app/models/book.rb
class Book < ApplicationRecord
  include Filterable

  has_many :manifests
  has_many :carts
  has_many :orders, through: :manifests
  has_many :opinions

  validates :title, :authors, :publisher, :format, :subject, presence: true
  validates :isbn,      presence: true, uniqueness: true, format: { with: /\A[0-9-]+\z/, message: "only allows numerical digits and hyphens" }, length: { in: 13..14 }
  validates :year,      presence: true, numericality: { only_integer: true }
  validates :inventory, presence: true, numericality: { only_integer: true }
  validates :price,     presence: true, numericality: true

  scope :title,     -> (title)     { where("lower(title) like ?", "%#{title.downcase}%") }
  scope :authors,   -> (authors)   { where("lower(authors) like ?", "%#{authors.downcase}%") }
  scope :publisher, -> (publisher) { where("lower(publisher) like ?", "%#{publisher.downcase}%") }
  scope :subject,   -> (subject)   { where("lower(subject) like ?", "%#{subject.downcase}%") }
  scope :from_this_month, lambda { where("orders.created_at > ? AND orders.created_at < ?", Time.now.beginning_of_month, Time.now.end_of_month) }
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin_rights

  def index
    @books = Book.filter(params.slice(:title, :authors, :publisher, :subject)).page(params[:page]).per(25)
    if params[:sort] == "year"
      @books = @books.order(year: :desc)
    elsif params[:sort] == "inventory"
      @books = @books.order(inventory: :desc)
    else
      @books = @books.order(title: :asc)
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to [:admin, @book], notice: 'New book was successfully created.'
    else
      render 'new'
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to [:admin, @book], notice: 'Book details were successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to admin_books_path, notice: 'Book was successfully deleted.'
  end

  def stats
    @books = Book.select('books.id, books.title, books.isbn, SUM(manifests.quantity) AS num_of_copies').joins('INNER JOIN manifests ON books.id = manifests.book_id').joins('INNER JOIN orders ON orders.id = manifests.order_id').group('books.id').from_this_month.order('SUM(manifests.quantity) DESC')
    if params[:book_num].present?
      @books = @books.limit(params[:book_num])
    else
      @books = @books.limit(10)
    end

    @authors = Book.select('books.authors, SUM(manifests.quantity) AS num_of_copies').joins('INNER JOIN manifests ON books.id = manifests.book_id').joins('INNER JOIN orders ON orders.id = manifests.order_id').group('books.authors').from_this_month.order('SUM(manifests.quantity) DESC')
    if params[:author_num].present?
      @authors = @authors.limit(params[:author_num])
    else
      @authors = @authors.limit(10)
    end

    @publishers = Book.select('books.publisher, SUM(manifests.quantity) AS num_of_copies').joins('INNER JOIN manifests ON books.id = manifests.book_id').joins('INNER JOIN orders ON orders.id = manifests.order_id').group('books.publisher').from_this_month.order('SUM(manifests.quantity) DESC')
    if params[:publisher_num].present?
      @publishers = @publishers.limit(params[:publisher_num])
    else
      @publishers = @publishers.limit(10)
    end
  end

  private

  def book_params
    params.require(:book).permit(:isbn, :title, :authors, :publisher, :year, :inventory, :price, :format, :keywords, :subject)
  end

  protected

  def check_admin_rights
    unless current_user.admin?
      redirect_to root_url, alert: "You do not have admin rights."
    end
  end
end

app/controllers/admins/books_controller.rb
class Admins::BooksController < ApplicationController
  
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to [:admins, @book], notice: 'New book was successfully created.'
    else
      render 'new'
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to [:admins, @book], notice: 'Book details were successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to admins_books_path, notice: 'Book was successfully deleted.'
  end

  private
    def book_params
      params.require(:book).permit(:isbn, :title, :authors, :publisher, :year, :inventory, :price, :format, :keywords, :subject)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.filter(params.slice(:title, :authors, :publisher, :subject)).page(params[:page]).per(24)
    if params[:sort] == "year"
      @books = @books.order(year: :desc)
    elsif params[:sort] == "review score"
      @books = @books.order('average_score DESC NULLS LAST')
    else
      @books = @books.order(created_at: :desc)
    end
  end

  def show
    @book = Book.find(params[:id])
    if params[:num].present?
      @opinions = @book.opinions.includes(:ratings).order('average_usefulness DESC NULLS LAST').limit(params[:num])
    else
      @opinions = @book.opinions.includes(:ratings).page(params[:page]).per(10)
    end
    if params[:recommend].present?
      @recommended = Book.find_by_sql("SELECT books.id, books.title, books.authors FROM books INNER JOIN (manifests INNER JOIN orders ON orders.id = manifests.order_id) ON books.id = manifests.book_id WHERE orders.user_id IN (SELECT orders.user_id FROM manifests, orders WHERE orders.id = manifests.order_id AND orders.user_id <> #{current_user.id} AND manifests.book_id = #{params[:id]}) AND books.id <> #{params[:id]} GROUP BY books.id ORDER BY SUM(manifests.quantity) DESC LIMIT 6")
    end
    if user_signed_in?
      @cart = Cart.new
      @opinion = Opinion.new
    end
  end
end

app/views/admin/books/_form.html.haml
= simple_form_for [:admin, @book] do |f|
  = f.input :isbn, label: 'ISBN-13', error: 'ISBN is mandatory, please specify one.'
  = f.input :title
  = f.input :authors, label: 'Author(s)'
  = f.input :publisher
  = f.input :year, label: 'Year of publication'
  = f.input :inventory, label: 'Number of copies'
  = f.input :price
  = f.input :format, collection: %w(hardcover paperback), prompt: '(Select book format)'
  = f.input :keywords
  = f.input :subject, placeholder: 'e.g. Science, History, Romance etc'
  = f.button :submit, class: 'expanded button'

app/views/admin/books/edit.html.haml
.row
  %h1 Edit Book

  = render 'form'
  = link_to 'Back', admin_book_path, class: 'secondary expanded button'

app/views/admin/books/index.html.haml
.row.admin-panel
  .medium-4.columns
    %h1 Book List
  .medium-3.columns
    .expanded.button-group
      = link_to 'Statistics', stats_admin_books_path, class: 'secondary button'
      = link_to 'New book', new_admin_book_path, class: 'button'

.row.search-sort
  = form_tag(admin_books_path, method: :get) do
    .medium-6.columns
      %ul.menu
        %li
          = hidden_field_tag :authors,   params[:authors]
          = hidden_field_tag :publisher, params[:publisher]
          = hidden_field_tag :subject,   params[:subject]
          .input-group
            = text_field_tag :title, params[:title], placeholder: "Search Title", class: "input-group-field"
            .input-group-button
              = submit_tag "Search", class: "button"
        %li
          %a.button.success.open-modal{"data-open": "adminAdvancedSearch"} More Filters
    .medium-3.columns
      .input-group
        %span.input-group-label Sort by
        = select_tag :sort, options_for_select(["year", "inventory"], params[:sort]), include_blank: true, onchange: "this.form.submit()", class: "input-group-field"

.row.column
  %table.hover
    %thead
      %tr
        %th Title
        %th ISBN
        %th Author(s)
        %th Publisher
        %th Year
        %th Inventory
        %th{colspan: "2"} Actions

    %tbody
      - @books.each do |book|
        %tr
          %td= book.title
          %td= book.isbn
          %td= book.authors
          %td= book.publisher
          %td= book.year
          %td
            = form_for book, url: admin_book_path(book), method: :patch do |f|
              = select("book", "inventory", 1..25, {selected: book.inventory}, {onchange: "this.form.submit()"})
          %td.vertical-aligned= link_to 'Show', admin_book_path(book), class: 'success button'
          %td.vertical-aligned= link_to 'Edit', edit_admin_book_path(book), class: 'warning button'

.row
  .float-right
    = paginate @books

= render "layouts/modal"

app/views/admin/books/new.html.haml
.row
  %h1 New Book

  = render 'form'
  = link_to 'Back', admin_books_path, class: 'expanded secondary button'

app/views/admin/books/show.html.haml
.row
  %h1= "#{@book.title}"
  %table
    %tbody
      %tr
        %td ISBN
        %td= @book.isbn
      %tr
        %td Author(s)
        %td= @book.authors
      %tr
        %td Publisher
        %td= @book.publisher
      %tr
        %td Year of publication
        %td= @book.year
      %tr
        %td Number of copies
        %td= @book.inventory
      %tr
        %td Price
        %td= number_to_currency(@book.price)
      %tr
        %td Format
        %td= @book.format
      %tr
        %td Keywords
        %td= @book.keywords
      %tr
        %td Subject
        %td= @book.subject

.row
  .expanded.button-group
    = link_to 'Back', admin_books_path, class: 'secondary button'
    = link_to 'Edit', edit_admin_book_path(@book), class: 'warning button'
    = link_to 'Delete', admin_book_path(@book), method: :delete, data: { confirm: 'Are you sure?' }, class: 'alert button'
    

app/views/admin/books/stats.html.haml
.row.column
  %h1 Most Popular
  %ul.tabs#stats{"data-tabs": ""}
    %li.tabs-title.is-active
      %a{"href": "#books-panel", "aria-selected": "true"} Books
    %li.tabs-title
      %a{"href": "#authors-panel"} Authors
    %li.tabs-title
      %a{"href": "#publishers-panel"} Publishers
  .tabs-content{"data-tabs-content": "stats"}
    .tabs-panel.is-active#books-panel
      .medium-5.medium-offset-7.columns
        = form_tag(stats_admin_books_path, method: :get) do
          .input-group
            %span.input-group-label Top
            = text_field_tag   :book_num,      params[:book_num] || 10, class: "input-group-field"
            = hidden_field_tag :author_num,    params[:author_num] || 10
            = hidden_field_tag :publisher_num, params[:publisher_num] || 10
            %span.input-group-label most popular book(s)
            .input-group-button
              = submit_tag "Search", class: "button"
      %table.hover
        %thead
          %tr
            %th Book Title
            %th ISBN
            %th Copies Sold
        %tbody
          - @books.each do |book|
            %tr
              %td
                = link_to admin_book_path(book) do
                  = book.title
              %td= book.isbn
              %td= book.num_of_copies
    .tabs-panel#authors-panel
      .medium-5.medium-offset-7.columns
        = form_tag(stats_admin_books_path, method: :get) do
          .input-group
            %span.input-group-label Top
            = text_field_tag   :author_num,    params[:author_num] || 10, class: "input-group-field"
            = hidden_field_tag :book_num,      params[:book_num] || 10
            = hidden_field_tag :publisher_num, params[:publisher_num] || 10
            %span.input-group-label most popular author(s)
            .input-group-button
              = submit_tag "Search", class: "button"
      %table.hover
        %thead
          %tr
            %th Authors
            %th Copies Sold
        %tbody
          - @authors.each do |author|
            %tr
              %td= author.authors
              %td= author.num_of_copies
    .tabs-panel#publishers-panel
      .medium-5.medium-offset-7.columns
        = form_tag(stats_admin_books_path, method: :get) do
          .input-group
            %span.input-group-label Top
            = text_field_tag   :publisher_num, params[:publisher_num] || 10, class: "input-group-field"
            = hidden_field_tag :book_num,      params[:book_num] || 10
            = hidden_field_tag :author_num,    params[:author_num] || 10
            %span.input-group-label most popular publisher(s)
            .input-group-button
              = submit_tag "Search", class: "button"
      %table.hover
        %thead
          %tr
            %th Publishers
            %th Copies Sold
        %tbody
          - @publishers.each do |publisher|
            %tr
              %td= publisher.publisher
              %td= publisher.num_of_copies