config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  namespace :admin do
    resources :books do
      get 'stats', on: :collection
    end
    root 'books#index'
  end

  resources :users, only: [:show]

  resources :books, only: [:index, :show, :update]

  resources :carts

  resources :orders, only: [:index, :create]

  resources :opinions, only: [:index, :create]

  resources :ratings, only: [:index, :create]

  root 'books#index'
end

app/models/book.rb
class Book < ApplicationRecord
  include Filterable

  has_many :manifests
  has_many :carts
  has_many :orders, through: :manifests
  has_many :opinions

  validates :title, :authors, :publisher, :format, :subject, presence: true
  validates :isbn,      presence: true, uniqueness: true, format: { with: /\A[0-9-]+\z/, message: "only allows numerical digits and hyphens" }, length: { in: 13..14 }
  validates :year,      presence: true, numericality: { only_integer: true }
  validates :inventory, presence: true, numericality: { only_integer: true }
  validates :price,     presence: true, numericality: true

  scope :title,     -> (title)     { where("lower(title) like ?", "%#{title.downcase}%") }
  scope :authors,   -> (authors)   { where("lower(authors) like ?", "%#{authors.downcase}%") }
  scope :publisher, -> (publisher) { where("lower(publisher) like ?", "%#{publisher.downcase}%") }
  scope :subject,   -> (subject)   { where("lower(subject) like ?", "%#{subject.downcase}%") }
  scope :from_this_month, lambda { where("orders.created_at > ? AND orders.created_at < ?", Time.now.beginning_of_month, Time.now.end_of_month) }
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin_rights

  def index
    @books = Book.filter(params.slice(:title, :authors, :publisher, :subject)).page(params[:page]).per(25)
    if params[:sort] == "year"
      @books = @books.order(year: :desc)
    elsif params[:sort] == "inventory"
      @books = @books.order(inventory: :desc)
    else
      @books = @books.order(title: :asc)
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to [:admin, @book], notice: 'New book was successfully created.'
    else
      render 'new'
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to [:admin, @book], notice: 'Book details were successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to admin_books_path, notice: 'Book was successfully deleted.'
  end

  def stats
    @books = Book.select('books.id, books.title, books.isbn, SUM(manifests.quantity) AS num_of_copies').joins('INNER JOIN manifests ON books.id = manifests.book_id').joins('INNER JOIN orders ON orders.id = manifests.order_id').group('books.id').from_this_month.order('SUM(manifests.quantity) DESC')
    if params[:book_num].present?
      @books = @books.limit(params[:book_num])
    else
      @books = @books.limit(10)
    end

    @authors = Book.select('books.authors, SUM(manifests.quantity) AS num_of_copies').joins('INNER JOIN manifests ON books.id = manifests.book_id').joins('INNER JOIN orders ON orders.id = manifests.order_id').group('books.authors').from_this_month.order('SUM(manifests.quantity) DESC')
    if params[:author_num].present?
      @authors = @authors.limit(params[:author_num])
    else
      @authors = @authors.limit(10)
    end

    @publishers = Book.select('books.publisher, SUM(manifests.quantity) AS num_of_copies').joins('INNER JOIN manifests ON books.id = manifests.book_id').joins('INNER JOIN orders ON orders.id = manifests.order_id').group('books.publisher').from_this_month.order('SUM(manifests.quantity) DESC')
    if params[:publisher_num].present?
      @publishers = @publishers.limit(params[:publisher_num])
    else
      @publishers = @publishers.limit(10)
    end
  end

  private

  def book_params
    params.require(:book).permit(:isbn, :title, :authors, :publisher, :year, :inventory, :price, :format, :keywords, :subject)
  end

  protected

  def check_admin_rights
    unless current_user.admin?
      redirect_to root_url, alert: "You do not have admin rights."
    end
  end
end

app/controllers/admins/books_controller.rb
class Admins::BooksController < ApplicationController
  
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to [:admins, @book], notice: 'New book was successfully created.'
    else
      render 'new'
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to [:admins, @book], notice: 'Book details were successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to admins_books_path, notice: 'Book was successfully deleted.'
  end

  private
    def book_params
      params.require(:book).permit(:isbn, :title, :authors, :publisher, :year, :inventory, :price, :format, :keywords, :subject)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.filter(params.slice(:title, :authors, :publisher, :subject)).page(params[:page]).per(24)
    if params[:sort] == "year"
      @books = @books.order(year: :desc)
    elsif params[:sort] == "review score"
      @books = @books.order('average_score DESC NULLS LAST')
    else
      @books = @books.order(created_at: :desc)
    end
  end

  def show
    @book = Book.find(params[:id])
    if params[:num].present?
      @opinions = @book.opinions.includes(:ratings).order('average_usefulness DESC NULLS LAST').limit(params[:num])
    else
      @opinions = @book.opinions.includes(:ratings).page(params[:page]).per(10)
    end
    if params[:recommend].present?
      @recommended = Book.find_by_sql("SELECT books.id, books.title, books.authors FROM books INNER JOIN (manifests INNER JOIN orders ON orders.id = manifests.order_id) ON books.id = manifests.book_id WHERE orders.user_id IN (SELECT orders.user_id FROM manifests, orders WHERE orders.id = manifests.order_id AND orders.user_id <> #{current_user.id} AND manifests.book_id = #{params[:id]}) AND books.id <> #{params[:id]} GROUP BY books.id ORDER BY SUM(manifests.quantity) DESC LIMIT 6")
    end
    if user_signed_in?
      @cart = Cart.new
      @opinion = Opinion.new
    end
  end
end

app/views/books/index.html.haml
.row.search-sort
  = form_tag(books_path, method: :get) do
    .medium-6.columns
      %ul.menu
        %li
          = hidden_field_tag :authors,   params[:authors]
          = hidden_field_tag :publisher, params[:publisher]
          = hidden_field_tag :subject,   params[:subject]
          .input-group
            = text_field_tag :title, params[:title], placeholder: "Search Title", class: "input-group-field"
            .input-group-button
              = submit_tag "Search", class: "button"
        %li
          %a.button.success.open-modal{"data-open": "advancedSearch"} More Filters
    .medium-3.columns
      .input-group
        %span.input-group-label Sort by
        = select_tag :sort, options_for_select(["year", "review score"], params[:sort]), include_blank: true, onchange: "this.form.submit()", class: "input-group-field"

-# .orbit{"role": "region", "aria-label": "Favorite Space Pictures", "data-orbit": ""}
-#   %ul.orbit-container
-#     %button.orbit-previous{"aria-label": "previous"}
-#       %span.show-for-sr Previous Slide
-#       &#9664;
-#     %button.orbit-next{"aria-label": "next"}
-#       %span.show-for-sr Next Slide
-#       &#9654;
-#     %li.orbit-slide.is-active
-#       = image_tag "http://placehold.it/2000x750"
-#     %li.orbit-slide
-#       = image_tag "http://placehold.it/2000x750"

.row.column.text-center
  %hr
  %h2 Our Latest Books
  %hr

.row.small-up-2.medium-up-3.large-up-6
  - @books.each do |book|
    .column
      = link_to book_path(book) do
        = image_tag 'http://placehold.it/250x350', class: "thumbnail"
        %h6= book.title
        %p= "by #{book.authors}"

.row.column
  .float-right
    = paginate @books

= render "layouts/modal"

app/views/books/show.html.haml
- unless @recommended.blank?
  .row.column
    %h3 Books you may also be interested in ...
  .row.small-up-2.medium-up-3.large-up-6
    - @recommended.each do |recom|
      .column
        = link_to book_path(recom) do
          = image_tag 'http://placehold.it/250x350', class: "thumbnail"
          %h6= recom.title
          %p= "by #{recom.authors}"
  %hr

.row
  .medium-3.columns
    = image_tag 'http://placehold.it/250x350', class: 'thumbnail'
  .medium-9.columns
    %h2= @book.title
    %table
      %tbody
        %tr
          %td.bold ISBN
          %td= @book.isbn
        %tr
          %td.bold Author(s)
          %td= @book.authors
        %tr
          %td.bold Publisher
          %td= @book.publisher
        %tr
          %td.bold Year of publication
          %td= @book.year
        %tr
          %td.bold Subject
          %td= @book.subject
        %tr
          %td.bold Format
          %td= @book.format
        %tr
          %td.bold Price
          %td= number_to_currency(@book.price)
    - if user_signed_in?
      - if @book.inventory == 0
        %h5.red This book is currently out of stock. Sorry!
      - else
        = simple_form_for @cart do |f|
          = f.input :quantity, collection: 1..@book.inventory, selected: 1
          = f.hidden_field :book_id, value: @book.id
          = f.button :submit, 'Add to Cart', class: 'large expanded button'

- unless @opinions.blank?
  %hr
  .row
    .medium-3.columns
      %h3 Reviews
    .medium-4.columns
      = form_tag(book_path(@book), method: :get) do
        .input-group
          %span.input-group-label Top
          = text_field_tag :num, params[:num], placeholder: "n", class: "input-group-field"
          %span.input-group-label most useful review(s)
          .input-group-button
            = submit_tag "Search", class: "button"
  .row.column
    - @opinions.each do |opinion|
      .media-object.stack-for-small
        .media-object-section
          = image_tag 'http://placehold.it/200x200', class: 'thumbnail'
        .media-object-section
          %h5= opinion.user.full_name
          %h6= "Score: #{opinion.score}"
          %p= opinion.comment
          .small.button-group
            = link_to "Very useful (#{opinion.ratings.where(usefulness: 2).count})", ratings_path(usefulness: 2, opinion_id: opinion.id), method: :post, class: "success hollow button"
            = link_to "Useful (#{opinion.ratings.where(usefulness: 1).count})", ratings_path(usefulness: 1, opinion_id: opinion.id), method: :post, class: "warning hollow button"
            = link_to "Useless (#{opinion.ratings.where(usefulness: 0).count})", ratings_path(usefulness: 0, opinion_id: opinion.id), method: :post, class: "alert hollow button"
  - unless params[:num].present?
    .row.column
      .float-right
        = paginate @opinions

- if user_signed_in?
  %hr
  .row.column
    %h3 My Review
    = simple_form_for @opinion do |f|
      = f.input :score, collection: 0..10, prompt: 'Select your score'
      = f.input :comment
      = f.hidden_field :book_id, value: @book.id
      = f.button :submit, class: 'expanded button'