config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  namespace :admin do
    resources :books do
      get 'stats', on: :collection
    end
    root 'books#index'
  end

  resources :users, only: [:show]

  resources :books, only: [:index, :show, :update]

  resources :carts

  resources :orders, only: [:index, :create]

  resources :opinions, only: [:index, :create]

  resources :ratings, only: [:index, :create]

  root 'books#index'
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates :book, :user, presence: true
  validates :quantity, numericality: { only_integer: true }
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def index
    @carts = current_user.carts.includes(:book)
    @total_price = total_price
  end

  def create
    @cart = current_user.carts.where(book_id: cart_params[:book_id]).take
    if @cart.blank?
      current_user.create_cart(cart_params)
    else
      @cart.update(quantity: @cart.quantity + cart_params[:quantity].to_i)
    end
    redirect_to book_path(cart_params[:book_id], recommend: true), notice: "Added to your cart successfully."
  end

  def update
    @cart = Cart.find(params[:id])
    @cart.update(cart_params)
    redirect_back fallback_location: carts_url, notice: "Item(s) in your cart were successfully updated."
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy
    redirect_to carts_path, notice: "Item(s) in your cart were successfully deleted."
  end

  private

  def cart_params
    params.require(:cart).permit(:quantity, :book_id)
  end

  def total_price
    sum = 0
    current_user.carts.each {|cart| sum += cart.book.price * cart.quantity}
    sum
  end
end

app/views/carts/index.html.haml
.row.column
  %h1 My Cart
  %p= "You've selected #{current_user.cart_count} book(s)!"
  - @carts.each do |cart|
    .row{"data-equalizer": "", "data-equalize-on": "medium"}
      .medium-2.columns{"data-equalizer-watch": ""}
        = link_to book_path(cart.book) do
          = image_tag 'http://placehold.it/250x350', class: "thumbnail"
      .medium-6.columns{"data-equalizer-watch": ""}
        = link_to book_path(cart.book) do
          %h4= cart.book.title
        %p= "Unit price: #{number_to_currency(cart.book.price)}"
        = form_for cart, url: cart_path(cart), method: :patch do |f|
          = f.label :quantity
          = select("cart", "quantity", 1..cart.book.inventory, {selected: cart.quantity}, {onchange: "this.form.submit()"})
      .medium-1.column{"data-equalizer-watch": ""}
        = link_to cart_path(cart), method: :delete, data: { confirm: 'Are you sure?' } do
          %i.fi-x

  - unless @carts.blank?
    %br
    .secondary.callout.center-aligned
      %h5= "Amount payable: #{number_to_currency(@total_price)}"
    = link_to "Checkout", orders_path, method: :post, class: "large expanded button"