config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  namespace :admin do
    resources :books do
      get 'stats', on: :collection
    end
    root 'books#index'
  end

  resources :users, only: [:show]

  resources :books, only: [:index, :show, :update]

  resources :carts

  resources :orders, only: [:index, :create]

  resources :opinions, only: [:index, :create]

  resources :ratings, only: [:index, :create]

  root 'books#index'
end

app/views/layouts/_alerts.html.haml
- if notice.present?
  .row.column
    .success.callout{"data-closable": ""}
      = notice
      %button.close-button{"aria-label": "Dismiss alert", type: "button", "data-close": ""}
        %span{"aria-hidden": "true"} &times;

- if alert.present?
  .row.column
    .alert.callout{"data-closable": ""}
      = alert
      %button.close-button{"aria-label": "Dismiss alert", type: "button", "data-close": ""}
        %span{"aria-hidden": "true"} &times;

app/views/layouts/_modal.html.haml
.reveal#advancedSearch{"data-reveal": ""}
  %h4 Filters
  = form_tag(books_path, method: :get) do
    .row
      .small-3.columns
        = label_tag "title", nil, class: "text-right middle"
      .small-9.columns
        = text_field_tag :title, params[:title]
    .row
      .small-3.columns
        = label_tag "authors", "Author(s)", class: "text-right middle"
      .small-9.columns
        = text_field_tag :authors, params[:authors]
    .row
      .small-3.columns
        = label_tag "publisher", nil, class: "text-right middle"
      .small-9.columns
        = text_field_tag :publisher, params[:publisher]
    .row
      .small-3.columns
        = label_tag "subject", nil, class: "text-right middle"
      .small-9.columns
        = text_field_tag :subject, params[:subject]
    = hidden_field_tag :sort, params[:sort]
    = submit_tag "Filter", class: "expanded button"

  %button.close-button{type: "button", "data-close": "", "aria-label": "Close modal"}
    %span{"aria-hidden": "true"} &times;

.reveal#adminAdvancedSearch{"data-reveal": ""}
  %h4 Filters
  = form_tag(admin_books_path, method: :get) do
    .row
      .small-3.columns
        = label_tag "title", nil, class: "text-right middle"
      .small-9.columns
        = text_field_tag :title, params[:title]
    .row
      .small-3.columns
        = label_tag "authors", "Author(s)", class: "text-right middle"
      .small-9.columns
        = text_field_tag :authors, params[:authors]
    .row
      .small-3.columns
        = label_tag "publisher", nil, class: "text-right middle"
      .small-9.columns
        = text_field_tag :publisher, params[:publisher]
    .row
      .small-3.columns
        = label_tag "subject", nil, class: "text-right middle"
      .small-9.columns
        = text_field_tag :subject, params[:subject]
    = hidden_field_tag :sort, params[:sort]
    = submit_tag "Filter", class: "expanded button"

  %button.close-button{type: "button", "data-close": "", "aria-label": "Close modal"}
    %span{"aria-hidden": "true"} &times;

app/views/layouts/_navbar.html.haml
.top-bar
  .row
    .top-bar-left
      %ul.menu
        %li.bold
          = link_to "B&N Bookstore", root_path
    .top-bar-right
      %ul.dropdown.menu{"data-dropdown-menu": ""}
        - if user_signed_in?
          %li
            = link_to carts_path do
              %i.fi-shopping-cart
              = "My Cart (#{current_user.cart_count})"
          %li.has-submenu
            = current_user.full_name
            %ul.submenu.menu.vertical{"data-submenu": ""}
              %li= link_to 'Order History', orders_path
              %li= link_to 'Review History', opinions_path
              %li= link_to 'Rating History', ratings_path
              %li= link_to 'Profile', user_path(current_user)
              %li= link_to 'Log out', destroy_user_session_path, method: :delete
        - else
          %li= link_to 'Log In', new_user_session_path
          %li= link_to 'Sign Up', new_user_registration_path

app/views/layouts/application.html.haml
!!! 5
%html{lang: "en" }
  %head
    %meta{charset: "utf-8" }
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0" }

    %title B&N Bookstore

    = stylesheet_link_tag "application"
    = javascript_include_tag "application", "data-turbolinks-track": true
    = csrf_meta_tag

  %body
    = render "layouts/navbar"
    = render "layouts/alerts"

    %br
    = yield